import type { Role, Permission } from "./permissions";

export const ROLE_DEFAULTS: Readonly<Record<Role, readonly Permission[]>> = {
  super_admin: [
    "dashboard.read",
    "alerts.read",
    "alerts.list",
    "alerts.details",
    "alerts.acknowledge",
    "alerts.resolve",
    "alerts.reopen",
    "alerts.analyze",
    "agents.read",
    "agents.list",
    "agents.manage",
    "users.read",
    "users.manage",
    "invites.manage",
    "roles.read",
    "roles.manage",
    "sessions.revoke",
    "audit.read",
    "settings.manage",
    "chat.use",
    "super_admins.manage",
    "overrides.manage",
  ],
  admin: [
    "dashboard.read",
    "alerts.read",
    "alerts.list",
    "alerts.details",
    "alerts.acknowledge",
    "alerts.resolve",
    "alerts.reopen",
    "alerts.analyze",
    "agents.read",
    "agents.list",
    "agents.manage",
    "users.read",
    "users.manage",
    "invites.manage",
    "roles.read",
    "sessions.revoke",
    "audit.read",
    "chat.use",
  ],
  user: [
    "dashboard.read",
    "alerts.read",
    "alerts.list",
    "alerts.details",
    "agents.read",
    "agents.list",
  ],
};
